//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbAsistenciaV2Entities : DbContext
    {
        public dbAsistenciaV2Entities()
            : base("name=dbAsistenciaV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAsistencia> tblAsistencia { get; set; }
        public virtual DbSet<tblHora> tblHora { get; set; }
        public virtual DbSet<tblMateria> tblMateria { get; set; }
        public virtual DbSet<tblRelaAlumMater> tblRelaAlumMater { get; set; }
        public virtual DbSet<tblRelaMaesMater> tblRelaMaesMater { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
    }
}
