//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsistencia
    {
        public int Id_Asistencia { get; set; }
        public Nullable<System.DateTime> FechaAsistencia { get; set; }
        public Nullable<System.TimeSpan> HoraInicioAsistencia { get; set; }
        public Nullable<System.TimeSpan> HoraFinAsistencia { get; set; }
        public string MateriaAsistencia { get; set; }
        public string NombreEstudianteAsistencia { get; set; }
        public string ApellidoEstudianteAsistencia { get; set; }
        public string NombreMaestroAsistencia { get; set; }
        public string ApellidoMaestreAsistencia { get; set; }
        public Nullable<int> Asistencia { get; set; }
    }
}
