//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHora
    {
        public int Id_Hora { get; set; }
        public string NombreMaestroHora { get; set; }
        public string ApellidoMaestroHora { get; set; }
        public string NombreCompletoMaestroHora { get; set; }
        public string UsuarioMaestroHora { get; set; }
        public string MateriaHora { get; set; }
        public Nullable<System.TimeSpan> InicioHora { get; set; }
        public Nullable<System.TimeSpan> FinHora { get; set; }
    }
}
