//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMateria
    {
        public int Id_Materia { get; set; }
        public string NombreMateria { get; set; }
        public string CodigoMateria { get; set; }
        public string SalaMateria { get; set; }
    }
}
