//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelaAlumMater
    {
        public int Id_RAM { get; set; }
        public string NombreAlumnoRAM { get; set; }
        public string ApellidoAlumnoRAM { get; set; }
        public string UsuarioAlumnoRAM { get; set; }
        public string NombreCompletoRAM { get; set; }
        public string MateriaRAM { get; set; }
        public Nullable<int> Asistencia { get; set; }
    }
}
