//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelaMaesMater
    {
        public int Id_RMM { get; set; }
        public string NombreMaestroRMM { get; set; }
        public string ApellidoMaestroRMM { get; set; }
        public string UsuarioMaestroRMM { get; set; }
        public string NombreCompletoRMM { get; set; }
        public string MateriaRMM { get; set; }
    }
}
