//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public int Id_Usuario { get; set; }
        public string NombreUsuario { get; set; }
        public string ApellidoUsuario { get; set; }
        public string UsernameUsuario { get; set; }
        public string PasswordUsuario { get; set; }
        public int TipoUsuario { get; set; }
        public string TituloUsuario { get; set; }
    }
}
